/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	sourcesv1alpha1 "github.com/YipYap-run/knative-source/pkg/apis/sources/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// YipYapSourceLister helps list YipYapSources.
// All objects returned here must be treated as read-only.
type YipYapSourceLister interface {
	// List lists all YipYapSources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sourcesv1alpha1.YipYapSource, err error)
	// YipYapSources returns an object that can list and get YipYapSources.
	YipYapSources(namespace string) YipYapSourceNamespaceLister
	YipYapSourceListerExpansion
}

// yipYapSourceLister implements the YipYapSourceLister interface.
type yipYapSourceLister struct {
	listers.ResourceIndexer[*sourcesv1alpha1.YipYapSource]
}

// NewYipYapSourceLister returns a new YipYapSourceLister.
func NewYipYapSourceLister(indexer cache.Indexer) YipYapSourceLister {
	return &yipYapSourceLister{listers.New[*sourcesv1alpha1.YipYapSource](indexer, sourcesv1alpha1.Resource("yipyapsource"))}
}

// YipYapSources returns an object that can list and get YipYapSources.
func (s *yipYapSourceLister) YipYapSources(namespace string) YipYapSourceNamespaceLister {
	return yipYapSourceNamespaceLister{listers.NewNamespaced[*sourcesv1alpha1.YipYapSource](s.ResourceIndexer, namespace)}
}

// YipYapSourceNamespaceLister helps list and get YipYapSources.
// All objects returned here must be treated as read-only.
type YipYapSourceNamespaceLister interface {
	// List lists all YipYapSources in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sourcesv1alpha1.YipYapSource, err error)
	// Get retrieves the YipYapSource from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*sourcesv1alpha1.YipYapSource, error)
	YipYapSourceNamespaceListerExpansion
}

// yipYapSourceNamespaceLister implements the YipYapSourceNamespaceLister
// interface.
type yipYapSourceNamespaceLister struct {
	listers.ResourceIndexer[*sourcesv1alpha1.YipYapSource]
}
