# Minimal sources.yipyap.run/v1alpha1 YipYapSource.
#
# Apply with `kubectl apply -f example.yaml` once the chart is installed.
# See https://docs.yipyap.run/integrations/knative/source-crd/ for the
# full reference.

apiVersion: sources.yipyap.run/v1alpha1
kind: YipYapSource
metadata:
  name: yipyap-source-example
  namespace: yipyap-sources
spec:
  # apiKeyRef is required. Name the Secret that contains your YipYap API key.
  # kubectl -n yipyap-sources create secret generic yipyap-creds \
  #   --from-literal=api-key=yy_...
  apiKeyRef:
    name: yipyap-creds
  # The Knative sink to which YipYap CloudEvents will be delivered.
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
