apiVersion: v1
kind: Service
metadata:
  name: yipyap-source-controller-manager
  namespace: {{ include "yipyap-source.namespace" . }}
  labels:
    {{- include "yipyap-source.labels" . | nindent 4 }}
    control-plane: yipyap-source-controller-manager
spec:
  selector:
    control-plane: yipyap-source-controller-manager
  ports:
    - name: https
      port: 443
      targetPort: 443
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
    {{- end }}
