{{- if .Values.serviceAccounts.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yipyap-source.controllerServiceAccountName" . }}
  namespace: {{ include "yipyap-source.namespace" . }}
  labels:
    {{- include "yipyap-source.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.serviceAccounts.webhook.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yipyap-source.webhookServiceAccountName" . }}
  namespace: {{ include "yipyap-source.namespace" . }}
  labels:
    {{- include "yipyap-source.labels" . | nindent 4 }}
{{- end }}
