apiVersion: v1
kind: Service
metadata:
  name: yipyap-source-webhook
  namespace: {{ include "yipyap-source.namespace" . }}
  labels:
    {{- include "yipyap-source.labels" . | nindent 4 }}
    role: yipyap-source-webhook
spec:
  selector:
    role: yipyap-source-webhook
  ports:
    - name: https-webhook
      port: 443
      targetPort: {{ .Values.webhook.port }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
    {{- end }}
